### ISSUE TITLE
Unit test with jest and AutoMapper

### ISSUE THREAD

**Issue by anrolmar** [nestjsx/automapper#288]
Hi. I have a controller that uses a mapper. I want to test its methods. I'm using jest, but when I run the tests, I have this error message:

```
TypeError: decorator is not a function

      2 | 
      3 | export class BlobMessage {
    > 4 |   @AutoMap()
        |                                 ^
      5 |   filePath: string;
      6 | 
      7 |   @AutoMap()

      at DecorateProperty (node_modules/reflect-metadata/Reflect.js:553:33)
      at Object.decorate (node_modules/reflect-metadata/Reflect.js:123:24)
      at __decorate (src/models/blob-message.ts:4:92)
      at Object.<anonymous> (src/models/blob-message.ts:5:3)
      at Object.<anonymous> (test/controllers/consumer/consumer.controller.spec.ts:4:1)

```
This is my test file:

```
import { Test, TestingModule } from '@nestjs/testing';

import { Logger } from '@nestjs/common';

jest.mock('@services/consumer/consumer.service');
jest.mock('nestjsx-automapper');

let controller: Controller;
let service: Service;

describe('ConsumerController', () => {
  let testingModule: TestingModule;

  beforeAll(async () => {
    testingModule = await Test.createTestingModule({
      controllers: [Controller],
      providers: [Service, Logger],
    }).compile();

    controller = testingModule.get<Controller>(Controller);
    service = testingModule.get<Service>(Service);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
    expect(service).toBeDefined();
  });
```

Any ideas?

**Comment by micalevisk** [comment]
Hi! I've been using jest+TS decorators with no worries. Did you put `import 'reflect-metadata'` in your setup file? (source: https://github.com/nestjs/nest/issues/1305)

**Comment by nartc** [comment]
@anrolmar I haven't been able to reproduce this. Can you provide a sample repo?

**Comment by anrolmar** [comment]
https://github.com/anrolmar/nestjs-automapper-testing

This is the error that I get:
```

Nest can't resolve dependencies of the QueueController (RabbitMQService, ConfigService, ?). Please make sure that the argument nestjs__AUTO_MAPPER__default at index [2] is available in the RootTestModule context.

    Potential solutions:
    - If nestjs__AUTO_MAPPER__default is a provider, is it part of the current RootTestModule?
    - If nestjs__AUTO_MAPPER__default is exported from a separate @Module, is that module imported within RootTestModule?
      @Module({
        imports: [ /* the Module containing nestjs__AUTO_MAPPER__default */ ]
      })
```

**Comment by micalevisk** [comment]
@anrolmar I think you're missing the `AutomapperModule.withMapper()` call in your `testingModule` module

**Comment by nartc** [comment]
@anrolmar what @micalevisk suggests would work. However, if you don't need a real instance of `AutoMapper`, I do expose `getMapperToken()` to provide a way to mock `Mapper`

```ts
{
   provide: getMapperToken(),
   useValue: {/* mock automapper here. */}
}
```

**Comment by nartc** [comment]
Closing due to inactivity

**Comment by latifuysal** [comment]
I have also faced this problem. Did you manage to make this work without mocking?
